# https://taskfile.dev
version: "3"

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  CURRENT_USER_ID:
    sh: id --user

vars:
  DOCKER_EXEC_API: docker compose exec --user $CURRENT_USER_ID api
  DOCKER_EXEC_ADMIN: docker compose exec --user $CURRENT_USER_ID admin
  # Fallback to run --rm if exec fails (machine not running) - simplified logic for now assuming up
  # Better approach: check availability or just assume user ran 'task up'

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task --list-all

  init:
    desc: "Initialize project"
    cmds:
      - task: up
      - task: api:install
      - task: admin:install
      - task: api:migrate

  test:
    desc: "Run all tests"
    cmds:
      - task: api:test
      - task: api:mutation
      - task: api:deptrac
      - task: admin:test
      - task: admin:mutation

  fix:
    desc: "Fix all projects (backend and frontend)"
    cmds:
      - task: api:cs:fix
      - task: admin:fix

  up:
    desc: "Start all services"
    aliases: [start, run]
    cmds:
      - docker compose up -d

  down:
    desc: "Stop all services"
    aliases: [stop]
    cmds:
      - docker compose down

  logs:
    desc: "View logs"
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  ps:
    desc: "Check containers status"
    aliases: [status]
    cmds:
      - docker compose ps

  # === Backend (API) ===
  api:shell:
    desc: "Enter API container shell"
    aliases: [shell]
    cmds:
      - docker compose exec api sh

  api:install:
    desc: "Install backend dependencies"
    cmds:
      - "{{.DOCKER_EXEC_API}} composer install"

  api:test:
    desc: "Run backend tests"
    aliases: [test]
    cmds:
      - "{{.DOCKER_EXEC_API}} composer test"

  api:lint:
    desc: "Run PHPStan"
    aliases: [lint]
    cmds:
      - "{{.DOCKER_EXEC_API}} composer lint"

  api:cs:
    desc: "Check codestyle"
    aliases: [cs]
    cmds:
      - "{{.DOCKER_EXEC_API}} composer cs"

  api:cs:fix:
    desc: "Fix codestyle"
    cmds:
      - "{{.DOCKER_EXEC_API}} composer cs:fix"

  api:mutation:
    desc: "Run mutation tests"
    aliases: [mutation]
    cmds:
      - "{{.DOCKER_EXEC_API}} composer mutation"

  api:deptrac:
    desc: "Run Deptrac architecture analysis"
    aliases: [deptrac]
    cmds:
      - "{{.DOCKER_EXEC_API}} vendor/bin/deptrac analyse --no-cache"

  api:migrate:
    desc: "Run database migrations"
    cmds:
      - "{{.DOCKER_EXEC_API}} vendor/bin/doctrine-migrations migrate --no-interaction"

  api:seed:admin:
    desc: "Create a new admin user (usage: task api:seed:admin -- <email> <password>)"
    cmds:
      - "{{.DOCKER_EXEC_API}} php bin/create-admin.php {{.CLI_ARGS}}"

  # === Frontend (Admin) ===
  admin:shell:
    desc: "Enter Admin container shell"
    cmds:
      - docker compose exec admin sh

  admin:install:
    desc: "Install frontend dependencies"
    cmds:
      - "docker compose exec --user root admin sh -c 'command -v pnpm >/dev/null || npm install -g pnpm'"
      - "{{.DOCKER_EXEC_ADMIN}} pnpm install"

  admin:test:
    desc: "Run frontend tests"
    cmds:
      - "{{.DOCKER_EXEC_ADMIN}} pnpm test"

  admin:lint:
    desc: "Run ESLint"
    cmds:
      - "{{.DOCKER_EXEC_ADMIN}} pnpm lint"

  admin:fix:
    desc: "Fix linting and formatting"
    cmds:
      - "{{.DOCKER_EXEC_ADMIN}} pnpm lint --fix"
      - "{{.DOCKER_EXEC_ADMIN}} pnpm format"

  admin:build:
    desc: "Build frontend"
    cmds:
      - "{{.DOCKER_EXEC_ADMIN}} pnpm build"

  admin:mutation:
    desc: "Run mutation tests"
    cmds:
      - "{{.DOCKER_EXEC_ADMIN}} pnpm mutation"

  # === CI ===
  ci:api:
    desc: "Run all backend CI checks"
    cmds:
      - task: api:install
      - task: api:lint
      - task: api:cs
      - task: api:test
      - task: api:deptrac
      - task: api:mutation

  ci:admin:
    desc: "Run all frontend CI checks"
    cmds:
      - task: admin:install
      - task: admin:lint
      - task: admin:test
      - task: admin:build

  fix:
    desc: "Fix all projects (backend and frontend)"
    cmds:
      - task: api:cs:fix
      - task: admin:fix
